services:
  - type: web
    name: ImpGame
    env: python
    branch: main
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
